import { z } from "zod";

export const possible_customer = z.object({
    interested: z.string(),
    fantasy_name: z.union([z.string(), z.null(), z.undefined()]),
    size_company: z.union([z.string(), z.null(), z.undefined()]),
    legal_nature: z.union([z.string(), z.null(), z.undefined()]),
    public_place: z.string(),
    number: z.string(),
    complement: z.union([z.string(), z.null(), z.undefined()]),
    neighborhood: z.string(),
    city: z.string(),
    uf: z.string(),
    cep: z.union([z.string(), z.null(), z.undefined()]),
    cpf_cnpj: z.string(),
    tel: z.union([z.string(), z.null(), z.undefined()]),
    email: z.union([z.string(), z.null(), z.undefined()]),
    date_issue: z.string(),
    type: z.string(),
    validity: z.string(),
    situation: z.boolean(),
    responsible_contact: z.union([z.string(), z.null(), z.undefined()]),
    contact_name: z.union([z.string(), z.null(), z.undefined()]),
    contact_situation: z.union([z.string(), z.null(), z.undefined()]),
    contact_date: z.union([z.string(), z.null(), z.undefined()]),
    contact_time: z.union([z.string(), z.null(), z.undefined()]),
    comments: z.union([z.string(), z.null(), z.undefined()]),
    opening: z.union([z.string(), z.null(), z.undefined()]),
    in_activity: z.union([z.string(), z.null(), z.undefined()]),
    type_company: z.union([z.string(), z.null(), z.undefined()]),
    status_company: z.union([z.string(), z.null(), z.undefined()]),
    date_situation: z.union([z.string(), z.null(), z.undefined()]),
    last_update: z.union([z.string(), z.null(), z.undefined()]),
    efr: z.union([z.string(), z.null(), z.undefined()]),
    reason_situation: z.union([z.string(), z.null(), z.undefined()]),
    special_situation: z.union([z.string(), z.null(), z.undefined()]),
    special_situation_date: z.union([z.string(), z.null(), z.undefined()]),
    share_capital: z.union([z.string(), z.null(), z.undefined()]),
    send_email: z.boolean(),
    customer_feedback: z.boolean()
});