export type possibleCustomersType = {
    id: string;
    interested: string;
    fantasy_name: string | null;
    size_company: string | null;
    legal_nature: string | null;
    public_place: string;
    number: string;
    complement: string | null;
    neighborhood: string;
    city: string;
    uf: string;
    cep: string | null;
    cpf_cnpj: string;
    tel: string | null;
    email: string | null;
    date_issue: string;
    type: string;
    validity: string;
    deadline_expire: string;
    situation: boolean;
    responsible_contact: string | null;
    contact_name: string | null;
    contact_situation: string | null;
    contact_date: string | null;
    contact_time: string | null;
    comments: string | null;
    opening: string | null;
    in_activity: string | null;
    type_company: string | null;
    status_company: string | null;
    date_situation: string | null;
    last_update: string | null;
    efr: string | null;
    reason_situation: string | null;
    special_situation: string | null;
    special_situation_date: string | null;
    share_capital: string | null;
    send_email: boolean;
    customer_feedback: boolean;
    update_at: Date;
    created_at: Date;
}