export const formatDataStartPossibleCustomer = (result_search: any)=> {
    return {
        interested: result_search.nome,
        fantasy_name: result_search.fantasia,
        size_company: result_search.porte,
        legal_nature: result_search.natureza_juridica,
        public_place: result_search.logradouro,
        number: result_search.numero,
        complement: result_search.complemento,
        neighborhood: result_search.bairro,
        city: result_search.municipio,
        uf: result_search.uf,
        cep: result_search.cep,
        tel: result_search.telefone,
        email: result_search.email,
        responsible_contact: "",
        contact_name: result_search.qsa.length > 0 ? result_search.qsa[0].nome : "",
        contact_situation: "",
        contact_date: "",
        contact_time: "",
        opening: result_search.abertura,
        in_activity: result_search.situacao,
        type_company: result_search.tipo,
        status_company: result_search.status,
        date_situation: result_search.data_situacao,
        last_update: result_search.ultima_atualizacao,
        efr: result_search.efr,
        reason_situation: result_search.motivo_situacao,
        special_situation: result_search.situacao_especial,
        special_situation_date: result_search.data_situacao_especial,
        share_capital: result_search.capital_social,
        send_email: false,
        customer_feedback: false
    }
}